### ISSUE TITLE
Version of the library without shadowed dependencies

### ISSUE THREAD

**Issue by avietrov** [zalando-incubator/nakadi-java#182]
The library comes with, among others, shadowed GSON library for JSON processing.
If domain objects require additional configuration for proper serialisation one needs to use shadowed version from within the library.

For example, if a field requires [@SerializedName](https://google.github.io/gson/apidocs/com/google/gson/annotations/SerializedName.html) annotation to work correctly, we need to import this annotation with `nakadi.shadow` prefix. This means that we introduce a dependency on the shadowed code that comes with the library.

One potential solution would be to push two version of the jar: with and without shadowed dependencies, similarly to how [kryo](https://github.com/EsotericSoftware/kryo#integration-with-maven) manages shadowed dependencies.

**Comment by dehora** [comment]
I think if this is limited to JSON handling, another option is to allow the JSON handler to be provided as an extension. The very first cut of this library had a JSON Provider option  but that was removed, unfortunately because some transformation tricks are needed to unify Nakadi's disjoint event types, and also JSON libs needed to be configured to conform to Zalando's JSON guidelines (eg date handling) which the Nakadi API depends on. Maybe it's time to add that provider option back. Realistically the vast majority of users will use Gson or Jackson and adding those two should be quick enough to do (Gson is basically there already). It might be cleaner than publishing shaded/non-shaded variants.

**Comment by dehora** [comment]
Closing this as JSON libs can be provided since 0.8.7. Gson is available as an extension library, and opening https://github.com/zalando-incubator/nakadi-java/issues/219 to track a Jackson option.
