### ISSUE TITLE
Is it possible to find or create subscription?

### ISSUE THREAD

**Issue by skokorin** [zalando-incubator/nakadi-java#185]
```
val subscriptionDef = new Subscription()
      .consumerGroup("")
      .eventType("")
      .owningApplication("")

val subscription = resource.tryFind(subscriptionDef.id()).fold(resource.create(subscriptionDef))(identity)
```

**Comment by avietrov** [comment]
Why do you need to search for a subscription? According to [nakadi swagger](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L834), when you do `POST` to `/subscriptions` nakadi tries to lookup an existing subscription identified by `(owning app, event types, consumer group)` and, if such exists, returns it instead of creating a new one.

**Comment by skokorin** [comment]
true, thank you
