### ISSUE TITLE
Session with stream id <id>  not found (422)

### ISSUE THREAD

**Issue by olayinkasf** [zalando-incubator/nakadi-java#212]
This is found in our logs for all the stream processors and it is not retryable even though the server is still up and running. 

- What is the root cause of this error?
- Also, Could the ExceptionSupport file be made publicly accessible to use in identifying non retryable errors and implement retry when necessary.

**Comment by dehora** [comment]
> What is the root cause of this error?

The Nakadi server has disconnected the client, and the session id it supplied on that connection is no longer honored by the server for updating the cursor, all attempts to checkpoint with that session will fail. See https://github.com/zalando-incubator/nakadi-java/issues/117 for more details. Recent releases have support for suppressing this error, there's an example in a test case here: [StreamProcessorTest.java#L610-L615](https://github.com/zalando-incubator/nakadi-java/blob/master/nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java#L610-L615)


> Also, Could the ExceptionSupport file be made publicly accessible

No plans to do that. The next release of the client will effectively have observer exceptions be retryable and if the observer wants to kill the pipeline it can throw an unretryable exception to force that. Anything that's a java `Error` will also cause the consumer pipeline to exit

**Comment by dehora** [comment]
> The next release of the client will effectively have observer exceptions be retryable as the default and if the observer wants to kill the pipeline it can throw an unretryable exception to signal that. 

This is available as [0.9.0](https://github.com/zalando-incubator/nakadi-java/releases/tag/0.9.0). The logic is now default-retry except for `Error` and `NonRetryableNakadiException`. See [ExceptionSupport.java#L32-L51](https://github.com/zalando-incubator/nakadi-java/blob/7a7e0149e50175290c7b176914747aa0732d3280/nakadi-java-client/src/main/java/nakadi/ExceptionSupport.java#L32-L51).  0.9.0's a breaking change release as per https://github.com/zalando-incubator/nakadi-java/issues/194. 

If more is needed, maybe a supplier of white/black list of exceptions could make sense, but I feel this is over-configuration. Most users want consumers to retry by default, as per 0.9.0, rather than the retry if certain exception policy of previous versions, so arguing in more flexibility I think needs to meet 
 a high bar.

**Comment by olayinkasf** [comment]
Perfect! Thanks 👍

**Comment by PetrGlad** [comment]
Looking at the list of 4xx exceptions in `nakadi.ExceptionSupport` I think that none of them (except, authorization) should be retried. E.g. one cannot continue after "stream id is not found", so observer cannot do anything to handle this, except, maybe reporting error.
